volumes:
  mysql_data:
  redis_data:

services:
  mysql:
    image: mysql:8
    ports:
      # Conectar el puerto local 3306 al puerto 3306 del contenedor
      - published: ${DEMO_MYSQL_PORT:-3306}
        target: 3306
    volumes:
      # Montar el volumen "mysql_data" en el contenedor:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: 3x4mpl3P455w0rd
      MYSQL_DATABASE: demo_development
      MYSQL_ROOT_PASSWORD: 3x4mpl3P455w0rd

  redis:
    image: redis:6-alpine
    ports:
      # Conectar el puerto local 6379 al puerto 6379 del contenedor
      - published: ${DEMO_REDIS_PORT:-6379}
        target: 6379
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - published: ${DEMO_MAILHOG_HTTP_PORT:-8025}
        target: 8025

  chrome:
    image: browserless/chrome:latest
    ports:
      - ${DEMO_CHROME_PORT:-3000}:3000
    environment:
      CONNECTION_TIMEOUT: 6000000
