name: CI and CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_image:
    name: Construir Imagen de Pruebas
    runs-on: ubuntu-latest
    steps:
      # Ver https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions
      - name: Obtener variables útiles
        id: ci-vars
        run: |-
          echo "::set-output name=RUNNER_UID::$(id -u)"
          echo "::set-output name=RUNNER_USER::$(whoami)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Test Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          target: testing
          build-args: |
            DEVELOPER_UID=${{ steps.ci-vars.outputs.RUNNER_UID }}
            DEVELOPER_USERNAME=${{ steps.ci-vars.outputs.RUNNER_USER }}
          tags: vovimayhem/php-demo:testing
          cache-from: type=gha
          cache-to: type=gha,mode=max

  run_tests:
    name: Correr Pruebas
    runs-on: ubuntu-latest
    needs:
      - build_test_image
    steps:
      - name: Obtener variables útiles
        id: ci-vars
        run: |-
          echo "::set-output name=RUNNER_UID::$(id -u)"
          echo "::set-output name=RUNNER_USER::$(whoami)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load Test Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          target: testing
          build-args: |
            DEVELOPER_UID=${{ steps.ci-vars.outputs.RUNNER_UID }}
            DEVELOPER_USERNAME=${{ steps.ci-vars.outputs.RUNNER_USER }}
          load: true
          tags: vovimayhem/php-demo:testing
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout
        uses: actions/checkout@v2

      - name: Correr pruebas
        env:
          UID: ${{ steps.ci-vars.RUNNER_UID }}
          USER: ${{ steps.ci-vars.RUNNER_USER }}
        run: docker-compose -f docker-compose.yml -f ci-compose.yml run tests

  build_release:
    name: Construir imagen desplegable
    runs-on: ubuntu-latest
    needs:
      - build_test_image
    steps:
      - name: Obtener variables útiles
        id: ci-vars
        run: |-
          echo "::set-output name=RUNNER_UID::$(id -u)"
          echo "::set-output name=RUNNER_USER::$(whoami)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push release image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          target: release
          build-args: |
            DEVELOPER_UID=${{ steps.ci-vars.outputs.RUNNER_UID }}
            DEVELOPER_USERNAME=${{ steps.ci-vars.outputs.RUNNER_USER }}
          # push: true
          tags: vovimayhem/php-demo:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
