name: CI and CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_image:
    name: Construir Imagen de Pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          target: testing
          tags: vovimayhem/php-demo:testing
          cache-from: type=gha
          cache-to: type=gha,mode=max

  run_tests:
    name: Correr Pruebas
    runs-on: ubuntu-latest
    needs:
      - build_test_image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          target: testing
          load: true
          tags: vovimayhem/php-demo:testing
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Correr pruebas
        run: |-
          docker image ls
          docker-compose -f docker-compose.yml -f ci-compose.yml run tests

  build_release:
    name: Construir imagen desplegable
    runs-on: ubuntu-latest
    needs:
      - build_test_image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          target: release
          # push: true
          tags: vovimayhem/php-demo:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
